### ISSUE TITLE
Update tfenv tool

### ISSUE THREAD

**Issue by kvendingoldo** [novekm/aws-amplify-cloudscape#3]
Hi. Great repo! I see that you use tfenv here:

https://github.com/novekm/amplify-with-terraform/blob/4230e633ec9e209e55b7f49d2350c7c9cd59b0d2/setup.sh#L25

I suggest you to switch to tenv: https://github.com/tofuutils/tenv:

* it is a successor of [tofuenv](https://github.com/tofuutils/tofuenv) and [tfenv](https://github.com/tfutils/tfenv)
* can manage versions of OpenTofu / Terraform / Terragrunt and Atmos
* does not require any dependencies like jq / bash / etc

**Comment by novekm** [comment]
Thanks! [tenv](https://github.com/tofuutils/tenv) looks nice! However for now we will likely continue to use tfenv for now. This repo is mainly to serve as the source repo for the workshop [Automating Deployment of AWS Amplify Apps with Terraform](https://catalog.workshops.aws/amplify-with-terraform/en-US). 

The workshop has a focus on Terraform, (not OpenTofu, Terragrunt or Atmos) and is using only during the initial configuration of the AWS Cloud9 environment. However customers can feel free to use whichever version manager this wish in their own environments (tfenv, tenv, etc.) We may consider updating this for future updates to the workshop. Closing this issue for now

**Comment by kvendingoldo** [comment]
got it, thanks. If will need any help, ping me
